version: '3'

services:
  giraphy-simple:
    build: "./"
#    volumes:
#      - ./:/app/graphql-server/lib/conf
    ports:
      - "3000:3000"
    networks:
      - app-net
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-net

volumes:
  mysql:

networks:
  app-net:
    driver: bridge
